Loggeronly:
  cron: '0 */2 * * * *'
  class: Alerter::Loggeronly
  queue: loggeronly
  args:
    'testing rescue schedule alerter logger every 2 hours'
  description: 'Runs the perform method in Alerter::Loggeronly'
ScrapeTheSource:
  cron: '30 6 * * 7'
  class: SourceProcessor
  queue: sourceprocessing
  description: 'Updates the results'
CleanTheMilestones:
  cron: '30 7 * * 2'
  class: MilestoneCleaner
  queue: milestonecleaner
  description: 'Cleans the milestones'
email_alert:
  cron: '0 6 * * *'
  class: Alerter::MailGunAlerter
  args:  'Hello from Alerter Mailgun'
  description: Runs the perform method in Alerter::MailGunAlerter
visit_trimmer
  cron: '30 7 * * 4'
  class visit_trimmer
  queue: visit_trimmer
  description: 'Stop the visits table getting too big'